// <auto-generated />
using System;
using CinemaAura.Infrastructure.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaAura.Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260116001232_MassiveRefactor")]
    partial class MassiveRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_actors_name");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_genres_name");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hall_name");

                    b.Property<int>("HorizontalSize")
                        .HasColumnType("integer")
                        .HasColumnName("horizontal_size");

                    b.Property<int>("VerticalSize")
                        .HasColumnType("integer")
                        .HasColumnName("vertical_size");

                    b.HasKey("Id");

                    b.ToTable("halls", null, t =>
                        {
                            t.HasCheckConstraint("ck_halls_horizontal_size_positive", "horizontal_size > 0");

                            t.HasCheckConstraint("ck_halls_vertical_size_positive", "vertical_size > 0");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("medias", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("age_limit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Rate")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rate");

                    b.HasKey("Id");

                    b.HasIndex("Rate")
                        .HasDatabaseName("ix_movies_rate");

                    b.ToTable("movies", null, t =>
                        {
                            t.HasCheckConstraint("ck_movies_age_limit_positive", "age_limit >= 0");

                            t.HasCheckConstraint("ck_movies_rate_range", "rate >= 0 AND rate <= 10");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid")
                        .HasColumnName("hall_id");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("number");

                    b.Property<short>("Row")
                        .HasColumnType("smallint")
                        .HasColumnName("row");

                    b.Property<Guid>("SeatTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_type_id");

                    b.HasKey("Id");

                    b.HasIndex("HallId")
                        .HasDatabaseName("ix_seats_hall_id");

                    b.HasIndex("SeatTypeId")
                        .HasDatabaseName("ix_seats_seat_type_id");

                    b.HasIndex("HallId", "Row", "Number")
                        .IsUnique()
                        .HasDatabaseName("uq_seats_position");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.SeatType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("uq_seat_types_type_name");

                    b.ToTable("seat_types", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid")
                        .HasColumnName("hall_id");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("HallId")
                        .HasDatabaseName("ix_sessions_hall_id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_sessions_movie_id");

                    b.HasIndex("StartDateTime")
                        .HasDatabaseName("ix_sessions_start_time");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("PricePaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_paid");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PurchasedAt")
                        .HasDatabaseName("ix_tickets_purchased_at");

                    b.HasIndex("SeatId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_tickets_session_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tickets_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tickets_user_id");

                    b.HasIndex("SessionId", "SeatId")
                        .IsUnique()
                        .HasDatabaseName("uq_tickets_session_seat");

                    b.ToTable("tickets", null, t =>
                        {
                            t.HasCheckConstraint("ck_tickets_price_positive", "price_paid >= 0");

                            t.HasCheckConstraint("ck_tickets_status_valid", "status IN ('Pending', 'Confirmed', 'Cancelled', 'Refunded')");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.TypePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("SeatTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_type_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SeatTypeId")
                        .HasDatabaseName("ix_type_prices_seat_type_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_type_prices_session_id");

                    b.HasIndex("SessionId", "SeatTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_type_prices_session_seat_type");

                    b.ToTable("type_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_type_prices_price_positive", "price >= 0");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Movie", b =>
                {
                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MovieActor", "_actorIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("actor_id");

                            b1.HasKey("movie_id", "ActorId");

                            b1.HasIndex("ActorId");

                            b1.ToTable("movie_actors", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Actor", null)
                                .WithMany()
                                .HasForeignKey("ActorId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MovieGenre", "_genreIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("GenreId")
                                .HasColumnType("uuid")
                                .HasColumnName("genre_id");

                            b1.HasKey("movie_id", "GenreId");

                            b1.HasIndex("GenreId");

                            b1.ToTable("movie_genres", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Genre", null)
                                .WithMany()
                                .HasForeignKey("GenreId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MovieMedia", "_mediaIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MediaId")
                                .HasColumnType("uuid")
                                .HasColumnName("media_id");

                            b1.HasKey("movie_id", "MediaId");

                            b1.HasIndex("MediaId");

                            b1.ToTable("movie_media", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Media", null)
                                .WithMany()
                                .HasForeignKey("MediaId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.Navigation("_actorIds");

                    b.Navigation("_genreIds");

                    b.Navigation("_mediaIds");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Role", b =>
                {
                    b.OwnsMany("CinemaAura.Domain.ValueObjects.PermissionCode", "_permissions", b1 =>
                        {
                            b1.Property<Guid>("role_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("permission_code");

                            b1.HasKey("role_id", "Value");

                            b1.HasIndex("role_id", "Value")
                                .IsUnique()
                                .HasDatabaseName("uq_role_permissions_role_permission");

                            b1.ToTable("role_permissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("role_id");
                        });

                    b.Navigation("_permissions");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Seat", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Hall", null)
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seats_halls_hall_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.SeatType", null)
                        .WithMany()
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seats_seat_types_seat_type_id");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Session", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Hall", null)
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_halls_hall_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_movies_movie_id");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_seats_seat_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_sessions_session_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tickets_users_user_id");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.TypePrice", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.SeatType", null)
                        .WithMany()
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_prices_seat_types_seat_type_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_prices_sessions_session_id");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.User", b =>
                {
                    b.OwnsOne("CinemaAura.Domain.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("password_salt");

                            b1.Property<byte[]>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("bytea")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.UserRole", "_roleIds", b1 =>
                        {
                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.HasKey("user_id", "RoleId");

                            b1.HasIndex("RoleId");

                            b1.ToTable("user_roles", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Role", null)
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("_roleIds");
                });
#pragma warning restore 612, 618
        }
    }
}
