// <auto-generated />
using System;
using CinemaAura.Infrastructure.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaAura.Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260115004747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HorizontalSize")
                        .HasColumnType("integer")
                        .HasColumnName("horizontal_size");

                    b.Property<int>("VerticalSize")
                        .HasColumnType("integer")
                        .HasColumnName("vertical_size");

                    b.HasKey("Id");

                    b.ToTable("Halls", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AgeLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("number");

                    b.Property<Guid>("SeatTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_type_id");

                    b.HasKey("Id");

                    b.ToTable("Seats", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.SeatType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.HasIndex("TypeName");

                    b.ToTable("SeatTypes", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid")
                        .HasColumnName("hall");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.TypePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("SeatTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_type_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SeatTypeId");

                    b.ToTable("TypePrices", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Unknown");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Movie", b =>
                {
                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MovieActor", "_actorIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("actor_id");

                            b1.HasKey("movie_id", "ActorId");

                            b1.HasIndex("ActorId");

                            b1.ToTable("movie_actors", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Actor", null)
                                .WithMany()
                                .HasForeignKey("ActorId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MovieGenre", "_genreIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("GenreId")
                                .HasColumnType("uuid")
                                .HasColumnName("genre_id");

                            b1.HasKey("movie_id", "GenreId");

                            b1.HasIndex("GenreId");

                            b1.ToTable("movie_genres", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Genre", null)
                                .WithMany()
                                .HasForeignKey("GenreId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MovieMedia", "_mediaIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MediaId")
                                .HasColumnType("uuid")
                                .HasColumnName("media_id");

                            b1.HasKey("movie_id", "MediaId");

                            b1.HasIndex("MediaId");

                            b1.ToTable("movie_media", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Media", null)
                                .WithMany()
                                .HasForeignKey("MediaId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.Navigation("_actorIds");

                    b.Navigation("_genreIds");

                    b.Navigation("_mediaIds");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Role", b =>
                {
                    b.OwnsMany("CinemaAura.Domain.ValueObjects.PermissionCode", "_permissions", b1 =>
                        {
                            b1.Property<Guid>("role_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("permission_code");

                            b1.HasKey("role_id", "Value");

                            b1.HasIndex("role_id", "Value")
                                .IsUnique();

                            b1.ToTable("role_permissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("role_id");
                        });

                    b.Navigation("_permissions");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Session", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Hall", null)
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AbsoluteCinema.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AbsoluteCinema.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AbsoluteCinema.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.User", b =>
                {
                    b.OwnsOne("CinemaAura.Domain.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<byte[]>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("bytea")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.UserRole", "_roleIds", b1 =>
                        {
                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.HasKey("user_id", "RoleId");

                            b1.HasIndex("RoleId");

                            b1.ToTable("user_roles", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Role", null)
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("_roleIds");
                });
#pragma warning restore 612, 618
        }
    }
}
