// <auto-generated />
using System;
using CinemaAura.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaAura.Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_genres_name");

                    b.ToTable("genres", null, t =>
                        {
                            t.HasCheckConstraint("ck_genres_name_not_empty", "LENGTH(name) > 0");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hall_name");

                    b.HasKey("Id");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("medias", null, t =>
                        {
                            t.HasCheckConstraint("ck_medias_status_valid", "type IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgeLimit")
                        .HasColumnType("integer")
                        .HasColumnName("age_limit");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Rate")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rate");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("studio");

                    b.HasKey("Id");

                    b.HasIndex("Rate")
                        .HasDatabaseName("ix_movies_rate");

                    b.ToTable("movies", null, t =>
                        {
                            t.HasCheckConstraint("ck_movies_age_limit_positive", "age_limit >= 0");

                            t.HasCheckConstraint("ck_movies_duration_positive", "duration > 0");

                            t.HasCheckConstraint("ck_movies_rate_range", "rate >= 0 AND rate <= 10");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_permission_has_not_whitespaces", "code NOT LIKE '% %'");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PersonRole")
                        .HasColumnType("integer")
                        .HasColumnName("person_role");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_actors_name");

                    b.ToTable("persons", null, t =>
                        {
                            t.HasCheckConstraint("ck_persons_name_not_empty", "LENGTH(name) > 0");

                            t.HasCheckConstraint("ck_persons_status_valid", "person_role IN (1, 2)");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid")
                        .HasColumnName("hall_id");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("number");

                    b.Property<short>("Row")
                        .HasColumnType("smallint")
                        .HasColumnName("row");

                    b.Property<Guid>("SeatTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_type_id");

                    b.HasKey("Id");

                    b.HasIndex("HallId")
                        .HasDatabaseName("ix_seats_hall_id");

                    b.HasIndex("SeatTypeId")
                        .HasDatabaseName("ix_seats_seat_type_id");

                    b.HasIndex("HallId", "Row", "Number")
                        .IsUnique()
                        .HasDatabaseName("uq_seats_position");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.SeatType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasDatabaseName("uq_seat_types_type_name");

                    b.ToTable("seat_types", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid")
                        .HasColumnName("hall_id");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("HallId")
                        .HasDatabaseName("ix_sessions_hall_id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_sessions_movie_id");

                    b.HasIndex("StartDateTime")
                        .HasDatabaseName("ix_sessions_start_time");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PurchasedAt")
                        .HasDatabaseName("ix_tickets_purchased_at");

                    b.HasIndex("SeatId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_tickets_session_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tickets_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tickets_user_id");

                    b.HasIndex("SessionId", "SeatId")
                        .IsUnique()
                        .HasDatabaseName("uq_tickets_session_seat");

                    b.ToTable("tickets", null, t =>
                        {
                            t.HasCheckConstraint("ck_tickets_status_valid", "status IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.TypePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("SeatTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_type_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SeatTypeId")
                        .HasDatabaseName("ix_type_prices_seat_type_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_type_prices_session_id");

                    b.HasIndex("SessionId", "SeatTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_type_prices_session_seat_type");

                    b.ToTable("type_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_type_prices_price_positive", "price >= 0");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_username_length", "LENGTH(user_name) >= 1");
                        });
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Movie", b =>
                {
                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MovieGenre", "_genreIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("GenreId")
                                .HasColumnType("uuid")
                                .HasColumnName("genre_id");

                            b1.HasKey("movie_id", "GenreId");

                            b1.HasIndex("GenreId");

                            b1.ToTable("movie_genres", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Genre", null)
                                .WithMany()
                                .HasForeignKey("GenreId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MovieMedia", "_mediaIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MediaId")
                                .HasColumnType("uuid")
                                .HasColumnName("media_id");

                            b1.HasKey("movie_id", "MediaId");

                            b1.HasIndex("MediaId");

                            b1.ToTable("movie_media", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Media", null)
                                .WithMany()
                                .HasForeignKey("MediaId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.MoviePerson", "_personIds", b1 =>
                        {
                            b1.Property<Guid>("movie_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("actor_id");

                            b1.HasKey("movie_id", "PersonId");

                            b1.HasIndex("PersonId");

                            b1.ToTable("movie_persons", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Person", null)
                                .WithMany()
                                .HasForeignKey("PersonId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("movie_id");
                        });

                    b.Navigation("_genreIds");

                    b.Navigation("_mediaIds");

                    b.Navigation("_personIds");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Person", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Media", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Media");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Role", b =>
                {
                    b.OwnsMany("AbsoluteCinema.Domain.Entities.RolePermission", "_permissionsIds", b1 =>
                        {
                            b1.Property<Guid>("role_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("uuid")
                                .HasColumnName("permission_id");

                            b1.HasKey("role_id", "PermissionId");

                            b1.HasIndex("PermissionId");

                            b1.ToTable("role_permissions", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Permission", null)
                                .WithMany()
                                .HasForeignKey("PermissionId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("role_id");
                        });

                    b.Navigation("_permissionsIds");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Seat", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Hall", null)
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_halls_hall_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.SeatType", null)
                        .WithMany()
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seats_seat_types_seat_type_id");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Session", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Hall", null)
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_halls_hall_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_movies_movie_id");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_seats_seat_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_sessions_session_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tickets_users_user_id");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.TypePrice", b =>
                {
                    b.HasOne("AbsoluteCinema.Domain.Entities.SeatType", null)
                        .WithMany()
                        .HasForeignKey("SeatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_prices_seat_types_seat_type_id");

                    b.HasOne("AbsoluteCinema.Domain.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_prices_sessions_session_id");
                });

            modelBuilder.Entity("AbsoluteCinema.Domain.Entities.User", b =>
                {
                    b.OwnsOne("CinemaAura.Domain.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("bytea")
                                .HasColumnName("password_salt");

                            b1.Property<byte[]>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("bytea")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("AbsoluteCinema.Domain.Entities.UserRole", "_roleIds", b1 =>
                        {
                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.HasKey("user_id", "RoleId");

                            b1.HasIndex("RoleId");

                            b1.ToTable("user_roles", (string)null);

                            b1.HasOne("AbsoluteCinema.Domain.Entities.Role", null)
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("_roleIds");
                });
#pragma warning restore 612, 618
        }
    }
}
