version: '3.8'
services:
  postgres_db:
    image: postgres:18
    container_name: cinema_postgres
    restart: always
    environment:
      - POSTGRES_DB=cinema_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_pass
      - TZ=Europe/Kyiv 
      - PGTZ=Europe/Kyiv 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: